=== estebanf/LaunchPointProcess/Schemas/integrations/getLaunchpointCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<element name="iob_response_root">
		<complexType>
			<sequence>
				<element name="CaseId" type="integer" />
				<element name="ClientId" type="integer" />
				<element name="ISOIndicator" type="integer" />
				<element name="Score" type="integer" />
				<element name="AccidentDate" type="date" />
				<element name="BenefitAmount" type="integer" />
				<element name="FundingSource" type="string" />
				<element name="LOB" type="string" />
				<element name="State" type="string" />
				<element name="WorkComp" type="string" />
				<element name="CaseStatus" type="string" />
				<element name="CaseSource" type="string" />
				<element name="SkipDuplicateCheck" type="boolean" />
				<element name="InvalidAddress" type="boolean" />
				<element name="LifecycleDescription" type="string" />
				<element name="CloseReason" type="string" />
                <element name="VipIndicator" type="boolean"></element>
                <element name="CreateDate" type="date" />
				<element name="ModifyDate" type="date" />
				<element name="CreatedBy" type="string" />
				<element name="ModifyBy" type="string" />
			</sequence>
		</complexType>
	</element>
</schema>

=== estebanf/LaunchPointProcess/Schemas/integrations/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<iob_response_root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="getLaunchpointCase.xsd">
  <CaseId>0</CaseId>
  <ClientId>0</ClientId>
  <ISOIndicator>0</ISOIndicator>
  <Score>0</Score>
  <AccidentDate>2001-01-01</AccidentDate>
  <BenefitAmount>0</BenefitAmount>
  <FundingSource>FundingSource</FundingSource>
  <LOB>LOB</LOB>
  <State>State</State>
  <WorkComp>WorkComp</WorkComp>
  <CaseStatus>CaseStatus</CaseStatus>
  <CaseSource>CaseSource</CaseSource>
  <SkipDuplicateCheck>true</SkipDuplicateCheck>
  <InvalidAddress>true</InvalidAddress>
  <LifecycleDescription>LifecycleDescription</LifecycleDescription>
  <CloseReason>CloseReason</CloseReason>
  <VipIndicator>true</VipIndicator>
  <CreateDate>2001-01-01</CreateDate>
  <ModifyDate>2001-01-01</ModifyDate>
  <CreatedBy>CreatedBy</CreatedBy>
  <ModifyBy>ModifyBy</ModifyBy>
</iob_response_root>
